# Generated by Django 4.1 on 2022-08-30 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('numbers_of_days', models.IntegerField(blank=True, null=True)),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearMonthDay.day')),
                ('objectives', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YearMonthDay.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('last_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', '2022'), ('1', '2023')], max_length=1)),
                ('starting_date', models.DateField(auto_now_add=True)),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearMonthDay.goal')),
                ('months', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearMonthDay.month')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YearMonthDay.task'),
        ),
    ]
