# Generated by Django 4.1 on 2022-08-30 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YearMonthDay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='name',
        ),
    ]
