# Generated by Django 4.1 on 2022-10-05 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YearMonthDay', '0002_year_goal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='user',
            field=models.ManyToManyField(related_name='years', to=settings.AUTH_USER_MODEL),
        ),
    ]
