# Generated by Django 4.1 on 2022-09-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YearMonthDay', '0002_remove_year_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='name',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='year',
            name='starting_date',
            field=models.DateField(),
        ),
    ]
