# Generated by Django 4.1 on 2022-09-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YearMonthDay', '0003_rename_name_day_number_alter_year_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='mes',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
