# Generated by Django 4.1 on 2022-09-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YearMonthDay', '0004_day_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='year',
            name='months',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
