# Generated by Django 4.1 on 2022-09-05 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YearMonthDay', '0005_remove_year_goals_remove_year_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YearMonthDay.day'),
        ),
    ]
