# Generated by Django 4.1 on 2022-09-05 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YearMonthDay', '0006_remove_day_tasks_task_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='days',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='YearMonthDay.day'),
        ),
    ]
