# Generated by Django 4.1 on 2022-09-14 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YearMonthDay', '0009_note_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='days',
            new_name='day',
        ),
    ]
